### PR TITLE
update regex

### PR DESCRIPTION
**Pull request by paradite**
I showed this repo to my friendly colleague, regex guru @lowjoel, and he pointed out that the regex can be further simplified and run more efficiently.

I did the performance testing and it is really the case:
https://jsperf.com/regex-gender-test/1

### CODE REVIEW

**Comment by db0company** [comment]
I like the original one better, the `*` emphasizes the concept of full inclusion :)

**Comment by klarstrup** [comment]
This is more inclusive, I approve.

**Comment by coquer** [comment]
Wow I actually can tell if this sadly real is pure fun sarcasms

**Comment by paradite** [comment]
This PR was just for fun. Time to close it.

**Comment by coquer** [comment]
What I mean is the repo, it really disappointed how they force "diversity " based on race and how you like to have sex with...

**Pull request closed without merging**
